trigger:
  branches:
    include:
      - main

variables:
  - group: dev-library

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deploy to Azure"
    jobs:
      - job: Terraform
        displayName: "Terraform Init, Plan, and Apply"
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: terraform init
            displayName: "Terraform Init"

          - script: terraform plan -out=tfplan
            displayName: "Terraform Plan"

          - script: terraform apply -auto-approve tfplan
            displayName: "Terraform Apply"
