trigger:
  branches:
    include:
      - main

variables:
  - group: dev-library

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Terraform_Deployment
    displayName: "Terraform Deploy to Azure"
    jobs:
      - job: Terraform
        displayName: "Terraform Init, Plan, and Apply"
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: main
            displayName: "Deploy resources"
            


